### PR TITLE
Windows notification support #2

### PR DESCRIPTION
**Pull request by JanVargovsky**
Duplicate of #18 since you merged it too soon :)
Dev of #9 

What was done:
- Added notification with a build result.
- Added notification with a test result.

### CODE REVIEW

**Comment by JanVargovsky** [comment]
Ready to merge, remaining original tasks are not that important right now. I will create separate issues for them.

**Comment by Bobris** [comment]
There are conflicts needs to be rebased.

**Comment by JanVargovsky** [comment]
"This branch has no conflicts with the base branch" 🤔

**Comment by Bobris** [comment]
Ah, ok I have selected "Rebase and merge" option:
This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch

Will use normal merge.

**Pull request merged**
